import {builtinModules} from 'node:module';
import { build } from 'esbuild';
import { mkdir, cp, writeFile, readFile, rm } from 'node:fs/promises';
import {resolve,sep} from 'node:path';
import {businessFooterHTML} from '../shared/site-info.js';
await mkdir('dist/server',{recursive:true});
await mkdir('dist/client',{recursive:true});
await cp('dist/app-ads.txt','dist/client/app-ads.txt');
await cp('dist/artist-gallery.js','dist/client/artist-gallery.js');
for(const file of ['chat-features.js','october-polish.css','canonical-origin.js','music-ui.js','music-experience.css','brand-refinement.css','account-settings.js','social-chat.js','recorder-worklet.js','improvements.js','improvements.css','recording-studio.css','sing-drafts.js','ads.txt','audio-ads.js','audio-ads.css','upload-ads.js','upload-ads.css','gifts.js','gifts.css','image-upload.js'])await cp(`dist/${file}`,`dist/client/${file}`);
// Delete the replaced, generated display-ad assets from incremental builds.
for(const file of ['web-ads.js','web-ads.css'])await rm(`dist/client/${file}`,{force:true});
await cp('dist/billing.js','dist/client/billing.js');
await cp('dist/gold-checkout.js','dist/client/gold-checkout.js');
await cp('dist/motion.js','dist/client/motion.js');
await cp('dist/motion.css','dist/client/motion.css');
await cp('dist/home.js','dist/client/home.js');
await cp('dist/brand.css','dist/client/brand.css');
for (const file of ['player-queue.css','community.js','community.css','polish.css','browse.js','browse.css','index.html','app.js','media-session.js','icons.js','views.js','studio.js','karaoke.js','lyrics.js','library.js','explorer.js','membership.js','alignment.js','actions.js','style.css','studio.css','lyrics.css','discovery.css','explorer.css','membership.css','alignment.css','policies.css','assets']) await cp(`dist/${file}`,`dist/client/${file}`,{recursive:true});
const indexHTML=await readFile('dist/index.html','utf8');
if(!indexHTML.includes('<!--BUSINESS_FOOTER-->'))throw new Error('Business footer placeholder is missing');
await writeFile('dist/client/index.html',indexHTML.replace('<!--BUSINESS_FOOTER-->',businessFooterHTML()));
await build({entryPoints:['shared/gifts.js'],outfile:'dist/client/gifts-core.js',bundle:true,format:'iife',globalName:'AifectGifts',target:'es2022',minify:true});
await build({entryPoints:['shared/site-info.js'],outfile:'dist/client/site-info.js',bundle:true,format:'iife',globalName:'AifectSite',target:'es2022',minify:true});
await build({entryPoints:['shared/genres.js'],outfile:'dist/client/genres-core.js',bundle:true,format:'iife',globalName:'AifectGenres',target:'es2022',minify:true});
await build({entryPoints:['shared/alignment.js'],outfile:'dist/client/alignment-core.js',bundle:true,format:'iife',globalName:'AifectAlignment',target:'es2022',minify:true});
await build({entryPoints:['shared/queue.js'],outfile:'dist/client/queue-core.js',bundle:true,format:'iife',globalName:'AifectQueue',target:'es2022',minify:true});
await build({entryPoints:['shared/audio-ads.js'],outfile:'dist/client/audio-ads-core.js',bundle:true,format:'iife',globalName:'AifectAudioAdsCore',target:'es2022',minify:true});
await build({entryPoints:['shared/vocal-worklet.js'],outfile:'dist/client/vocal-worklet.js',bundle:true,format:'esm',target:'es2022',minify:true});
await build({entryPoints:['shared/duet-guide.js'],outfile:'dist/client/duet-guide-core.js',bundle:true,format:'iife',globalName:'AifectDuetGuide',target:'es2022',minify:true});
await build({entryPoints:['shared/karaoke-audio.js'],outfile:'dist/client/karaoke-core.js',bundle:true,format:'iife',globalName:'AifectKaraoke',target:'es2022',minify:true});
await build({entryPoints:['shared/lyrics.js'],outfile:'dist/client/lyrics-core.js',bundle:true,format:'iife',globalName:'AifectLyrics',target:'es2022',minify:true});
await build({entryPoints:['server/index.js'], outfile:'dist/server/index.js', bundle:true, format:'esm', platform:'neutral', mainFields:['module','main'], alias:{'node-fetch':resolve('server/apple-fetch.js')}, banner:{js:"import {createRequire as appleCreateRequire} from 'node:module'; const require=appleCreateRequire('/aifect-worker.js');"}, target:'es2022', external:['cloudflare:workers',...builtinModules,...builtinModules.map(x=>'node:'+x)], minify:false});
await mkdir('dist/.openai',{recursive:true});
await cp('.openai/hosting.json','dist/.openai/hosting.json');
// Replace generated migration output: renamed source files must never remain in a release archive.
const migrationOutput=resolve('dist/.openai/drizzle'),metadataRoot=resolve('dist/.openai');
if(!migrationOutput.startsWith(metadataRoot+sep))throw new Error('Migration output is outside the build directory');
await rm(migrationOutput,{recursive:true,force:true});
await cp('drizzle',migrationOutput,{recursive:true});
await writeFile('dist/server/wrangler.json',JSON.stringify({main:'index.js',compatibility_date:'2026-09-01',assets:{directory:'../client',binding:'ASSETS'}}));
