import { sqliteTable, text, integer, real, primaryKey, index, uniqueIndex, check } from 'drizzle-orm/sqlite-core';
import { sql } from 'drizzle-orm';
export const users=sqliteTable('users',{
 id:text('id').primaryKey(), email:text('email').notNull(), name:text('name').notNull(), password:text('password'), provider:text('provider').notNull().default('email'), subject:text('subject'), created:integer('created').notNull(), premiumUntil:integer('premium_until').notNull().default(0), playlistSelection:text('playlist_selection').notNull().default('[]')
},t=>[uniqueIndex('users_identity').on(t.provider,t.subject),uniqueIndex('users_email_provider').on(t.email,t.provider)]);
export const sessions=sqliteTable('sessions',{token:text('token').primaryKey(),userId:text('user_id').notNull().references(()=>users.id,{onDelete:'cascade'}),expires:integer('expires').notNull()});
export const oauth=sqliteTable('oauth_states',{state:text('state').primaryKey(),provider:text('provider').notNull(),verifier:text('verifier').notNull(),nonce:text('nonce').notNull(),expires:integer('expires').notNull()});
export const producers=sqliteTable('producers',{id:text('id').primaryKey(),userId:text('user_id').notNull().references(()=>users.id),name:text('name').notNull(),bio:text('bio').notNull().default(''),imageVersion:text('image_version').notNull().default(''),imageType:text('image_type').notNull().default(''),bannerVersion:text('banner_version').notNull().default(''),bannerType:text('banner_type').notNull().default(''),created:integer('created').notNull()},t=>[uniqueIndex('producers_owner').on(t.userId)]);
export const artists=sqliteTable('artists',{id:text('id').primaryKey(),producerId:text('producer_id').notNull().references(()=>producers.id),name:text('name').notNull(),bio:text('bio').notNull().default(''),imageVersion:text('image_version').notNull().default(''),imageType:text('image_type').notNull().default(''),genre:text('genre').notNull().default(''),created:integer('created').notNull()},t=>[index('artists_producer').on(t.producerId)]);
export const tracks=sqliteTable('tracks',{
 id:text('id').primaryKey(),userId:text('user_id').notNull().references(()=>users.id),artistId:text('artist_id').notNull().references(()=>artists.id),producerId:text('producer_id').notNull().references(()=>producers.id),title:text('title').notNull(),genre:text('genre').notNull(),tags:text('tags').notNull().default(''),description:text('description').notNull().default(''),lyrics:text('lyrics').notNull().default(''),lyricsMode:text('lyrics_mode').notNull().default('none'),aiTool:text('ai_tool').notNull(),isAi:integer('is_ai').notNull().default(1),participation:text('participation').notNull().default(''),rightsAccepted:integer('rights_accepted').notNull(),status:text('status').notNull().default('uploading'),originalExt:text('original_ext').notNull(),originalBytes:integer('original_bytes').notNull(),duration:real('duration').notNull().default(0),hasCover:integer('has_cover').notNull().default(0),coverVersion:text('cover_version').notNull().default(''),coverType:text('cover_type').notNull().default(''),error:text('error'),created:integer('created').notNull(),leaseUntil:integer('lease_until').notNull().default(0),leaseToken:text('lease_token'),attempts:integer('attempts').notNull().default(0),karaokeTerms:text('karaoke_terms').notNull().default(''),karaokeAt:integer('karaoke_at').notNull().default(0),kind:text('kind').notNull().default('original'),originalId:text('original_id')
},t=>[index('tracks_status_created').on(t.status,t.created),index('tracks_original').on(t.originalId,t.status),index('tracks_user').on(t.userId),index('tracks_artist').on(t.artistId),index('tracks_producer').on(t.producerId)]);
export const likes=sqliteTable('likes',{userId:text('user_id').notNull().references(()=>users.id,{onDelete:'cascade'}),trackId:text('track_id').notNull().references(()=>tracks.id,{onDelete:'cascade'}),created:integer('created').notNull()},t=>[primaryKey({columns:[t.userId,t.trackId]}),index('likes_track').on(t.trackId)]);
export const follows=sqliteTable('follows',{userId:text('user_id').notNull().references(()=>users.id,{onDelete:'cascade'}),kind:text('kind').notNull(),targetId:text('target_id').notNull(),created:integer('created').notNull()},t=>[primaryKey({columns:[t.userId,t.kind,t.targetId]}),index('follows_target').on(t.kind,t.targetId)]);
export const comments=sqliteTable('comments',{id:text('id').primaryKey(),trackId:text('track_id').notNull().references(()=>tracks.id,{onDelete:'cascade'}),userId:text('user_id').notNull().references(()=>users.id,{onDelete:'cascade'}),parentId:text('parent_id'),body:text('body').notNull(),timestamp:real('timestamp'),created:integer('created').notNull(),edited:integer('edited')},t=>[index('comments_track').on(t.trackId,t.created)]);
export const commentLikes=sqliteTable('comment_likes',{userId:text('user_id').notNull().references(()=>users.id,{onDelete:'cascade'}),commentId:text('comment_id').notNull().references(()=>comments.id,{onDelete:'cascade'})},t=>[primaryKey({columns:[t.userId,t.commentId]})]);
export const playlists=sqliteTable('playlists',{id:text('id').primaryKey(),userId:text('user_id').notNull().references(()=>users.id,{onDelete:'cascade'}),name:text('name').notNull(),description:text('description').notNull().default(''),isPublic:integer('is_public').notNull().default(0),created:integer('created').notNull()},t=>[index('playlists_owner').on(t.userId)]);
export const playlistTracks=sqliteTable('playlist_tracks',{playlistId:text('playlist_id').notNull().references(()=>playlists.id,{onDelete:'cascade'}),trackId:text('track_id').notNull().references(()=>tracks.id,{onDelete:'cascade'}),created:integer('created').notNull(),position:integer('position').notNull().default(0)},t=>[primaryKey({columns:[t.playlistId,t.trackId]})]);
export const playlistSaves=sqliteTable('playlist_saves',{userId:text('user_id').notNull().references(()=>users.id,{onDelete:'cascade'}),playlistId:text('playlist_id').notNull().references(()=>playlists.id,{onDelete:'cascade'}),created:integer('created').notNull()},t=>[primaryKey({columns:[t.userId,t.playlistId]}),index('playlist_saves_playlist').on(t.playlistId)]);
export const playlistPreferences=sqliteTable('playlist_preferences',{userId:text('user_id').notNull().references(()=>users.id,{onDelete:'cascade'}),playlistId:text('playlist_id').notNull().references(()=>playlists.id,{onDelete:'cascade'}),pinned:integer('pinned').notNull().default(0),position:integer('position').notNull().default(0)},t=>[primaryKey({columns:[t.userId,t.playlistId]})]);
export const listens=sqliteTable('listens',{id:text('id').primaryKey(),trackId:text('track_id').notNull().references(()=>tracks.id,{onDelete:'cascade'}),listener:text('listener').notNull(),userId:text('user_id').references(()=>users.id,{onDelete:'cascade'}),started:integer('started').notNull(),seconds:real('seconds').notNull().default(0),day:text('day').notNull(),qualified:integer('qualified').notNull().default(0)},t=>[index('listens_track_day').on(t.trackId,t.day),index('listens_user_time').on(t.userId,t.started)]);
export const limits=sqliteTable('rate_limits',{key:text('key').primaryKey(),count:integer('count').notNull(),expires:integer('expires').notNull()});
export const billingTerms=sqliteTable('billing_terms',{version:text('version').primaryKey(),body:text('body').notNull(),created:integer('created').notNull()});
export const subscriptions=sqliteTable('billing_subscriptions',{
 id:text('id').primaryKey(),userId:text('user_id').notNull().references(()=>users.id),state:text('state').notNull(),bidCipher:text('bid_cipher'),cardName:text('card_name').notNull().default(''),cancelRequested:integer('cancel_requested').notNull().default(0),periodStart:integer('period_start').notNull().default(0),periodEnd:integer('period_end').notNull().default(0),cycle:integer('cycle').notNull().default(0),anchorDay:integer('anchor_day').notNull(),lastPaymentId:text('last_payment_id'),consentVersion:text('consent_version').notNull(),consentAt:integer('consent_at').notNull(),price:integer('price').notNull(),baselineUntil:integer('baseline_until').notNull().default(0),leaseToken:text('lease_token'),leaseUntil:integer('lease_until').notNull().default(0),created:integer('created').notNull(),updated:integer('updated').notNull()
},t=>[uniqueIndex('billing_subscription_user').on(t.userId),index('billing_subscription_due').on(t.state,t.cancelRequested,t.periodEnd)]);
export const billingPayments=sqliteTable('billing_payments',{
 id:text('id').primaryKey(),subscriptionId:text('subscription_id').notNull().references(()=>subscriptions.id),cycle:integer('cycle').notNull(),amount:integer('amount').notNull(),status:text('status').notNull(),tid:text('tid'),periodStart:integer('period_start').notNull(),periodEnd:integer('period_end').notNull(),entitlementEnd:integer('entitlement_end').notNull().default(0),refunded:integer('refunded').notNull().default(0),created:integer('created').notNull(),updated:integer('updated').notNull(),lastChecked:integer('last_checked').notNull().default(0),submittedAt:integer('submitted_at').notNull().default(0)
},t=>[uniqueIndex('billing_payment_cycle').on(t.subscriptionId,t.cycle),uniqueIndex('billing_payment_tid').on(t.tid),index('billing_payment_status').on(t.status,t.lastChecked)]);
export const billingWorker=sqliteTable('billing_worker',{id:text('id').primaryKey(),lastSeen:integer('last_seen').notNull()});
export const lyricJobs=sqliteTable('lyric_jobs',{
 trackId:text('track_id').primaryKey().references(()=>tracks.id,{onDelete:'cascade'}),id:text('id').notNull(),sourceText:text('source_text').notNull(),language:text('language').notNull(),state:text('state').notNull().default('queued'),resultLrc:text('result_lrc').notNull().default(''),needsAttention:integer('needs_attention').notNull().default(0),attempts:integer('attempts').notNull().default(0),leaseUntil:integer('lease_until').notNull().default(0),leaseToken:text('lease_token'),error:text('error'),created:integer('created').notNull(),updated:integer('updated').notNull()
},t=>[uniqueIndex('lyric_jobs_id').on(t.id),index('lyric_jobs_queue').on(t.state,t.leaseUntil,t.created)]);
// One karaoke build per track: MR (separated or creator-supplied) plus word timings aligned on the separated vocals.
export const karaokeJobs=sqliteTable('karaoke_jobs',{
 trackId:text('track_id').primaryKey().references(()=>tracks.id,{onDelete:'cascade'}),id:text('id').notNull(),state:text('state').notNull().default('queued'),mrSource:text('mr_source').notNull().default('auto'),mrExt:text('mr_ext').notNull().default(''),mrBytes:integer('mr_bytes').notNull().default(0),mrReady:integer('mr_ready').notNull().default(0),vocalsReady:integer('vocals_ready').notNull().default(0),lyricsText:text('lyrics_text').notNull().default(''),language:text('language').notNull().default('ko'),words:text('words').notNull().default(''),wordsState:text('words_state').notNull().default('none'),attempts:integer('attempts').notNull().default(0),leaseUntil:integer('lease_until').notNull().default(0),leaseToken:text('lease_token'),error:text('error'),created:integer('created').notNull(),updated:integer('updated').notNull()
},t=>[uniqueIndex('karaoke_jobs_id').on(t.id),index('karaoke_jobs_queue').on(t.state,t.leaseUntil,t.created)]);
// Gold is bought in lots; gifts spend the oldest paid lots first. The check keeps a lot from being overspent
// or spent once refunded, so a concurrent gift or refund rolls its whole batch back instead of corrupting balances.
export const goldPurchases=sqliteTable('gold_purchases',{
 id:text('id').primaryKey(),userId:text('user_id').notNull().references(()=>users.id),channel:text('channel').notNull(),gold:integer('gold').notNull(),used:integer('used').notNull().default(0),priceKrw:integer('price_krw').notNull(),feeKrw:integer('fee_krw').notNull().default(0),status:text('status').notNull().default('pending'),providerRef:text('provider_ref'),created:integer('created').notNull(),paidAt:integer('paid_at').notNull().default(0)
},t=>[index('gold_purchases_user').on(t.userId,t.status,t.paidAt),uniqueIndex('gold_purchases_ref').on(t.channel,t.providerRef),check('gold_purchases_usage',sql`${t.used} >= 0 AND ${t.used} <= ${t.gold} AND (${t.status} = 'paid' OR ${t.used} = 0)`)]);
// Shares are frozen per gift in milli-won: the cover singer, the original's creator and the platform.
export const gifts=sqliteTable('gifts',{
 id:text('id').primaryKey(),senderId:text('sender_id').notNull().references(()=>users.id),trackId:text('track_id').notNull().references(()=>tracks.id),gold:integer('gold').notNull(),netMw:integer('net_mw').notNull(),singerProfileId:text('singer_profile_id'),creatorProfileId:text('creator_profile_id').notNull(),singerMw:integer('singer_mw').notNull().default(0),creatorMw:integer('creator_mw').notNull(),platformMw:integer('platform_mw').notNull(),month:text('month').notNull(),created:integer('created').notNull()
},t=>[index('gifts_track').on(t.trackId,t.created),index('gifts_sender').on(t.senderId,t.created),index('gifts_singer').on(t.singerProfileId,t.month),index('gifts_creator').on(t.creatorProfileId,t.month)]);
export const giftLots=sqliteTable('gift_lots',{
 giftId:text('gift_id').notNull().references(()=>gifts.id),purchaseId:text('purchase_id').notNull().references(()=>goldPurchases.id),gold:integer('gold').notNull(),netMw:integer('net_mw').notNull()
},t=>[primaryKey({columns:[t.giftId,t.purchaseId]})]);
// Creator payout details. Account and resident numbers are stored only as AES-GCM ciphertext bound to the user.
export const payoutAccounts=sqliteTable('payout_accounts',{
 userId:text('user_id').primaryKey().references(()=>users.id),holder:text('holder').notNull(),bank:text('bank').notNull(),accountLast4:text('account_last4').notNull(),accountCipher:text('account_cipher').notNull(),residentHint:text('resident_hint').notNull(),residentCipher:text('resident_cipher').notNull(),consentAt:integer('consent_at').notNull(),updated:integer('updated').notNull()
});
export const payoutPeriods=sqliteTable('payout_periods',{period:text('period').primaryKey(),closedAt:integer('closed_at').notNull(),closedBy:text('closed_by').notNull()});
// One statement per profile per closed month; it covers every unpaid month since that profile's previous statement.
export const payoutStatements=sqliteTable('payout_statements',{
 id:text('id').primaryKey(),profileId:text('profile_id').notNull().references(()=>producers.id),userId:text('user_id').notNull().references(()=>users.id),period:text('period').notNull(),fromMonth:text('from_month').notNull(),grossKrw:integer('gross_krw').notNull(),incomeTaxKrw:integer('income_tax_krw').notNull().default(0),localTaxKrw:integer('local_tax_krw').notNull().default(0),netKrw:integer('net_krw').notNull(),status:text('status').notNull(),dueOn:text('due_on').notNull(),paidAt:integer('paid_at').notNull().default(0),paidRef:text('paid_ref'),paidBy:text('paid_by'),accountSnapshot:text('account_snapshot'),created:integer('created').notNull()
},t=>[uniqueIndex('payout_statements_period').on(t.profileId,t.period),index('payout_statements_status').on(t.status,t.dueOn),index('payout_statements_user').on(t.userId)]);
export const adminAudit=sqliteTable('admin_audit',{id:text('id').primaryKey(),adminId:text('admin_id').notNull(),action:text('action').notNull(),target:text('target').notNull(),created:integer('created').notNull()},t=>[index('admin_audit_time').on(t.created)]);
