import test from 'node:test';import assert from 'node:assert/strict';import {fixture} from './fixture.mjs';import {detectVocalActivity,remainingRanges,linePart,lineRole} from '../shared/duet-guide.js';
const body={original_id:'one',extension:'wav',bytes:128,own_voice:true,rights:true,cover_mode:'duet',duet_slot:'first',duet_consent:true};
const words=[{s:1,w:[{s:1,e:3,t:'첫 파트'}]},{s:5,w:[{s:5,e:7,t:'다음 파트'}]}];
async function setup(t){const f=await fixture(t);f.sql.exec("UPDATE tracks SET karaoke_at=1,duration=10 WHERE id='one'");f.sql.prepare("INSERT INTO karaoke_jobs(track_id,id,state,mr_ready,words,words_state,created,updated) VALUES('one','job','ready',1,?,'ready',0,0)").run(JSON.stringify(words));return f;}
test('dry vocal guide ignores silence and cable rumble, follows sync offset and retains partial lyric gaps',()=>{const rate=48000,samples=new Float32Array(rate*10);for(let i=0;i<samples.length;i++){samples[i]=.002*Math.sin(i*2*Math.PI*900/rate)+.004*Math.sin(i*2*Math.PI*30/rate);if(i>=rate&&i<rate*3)samples[i]+=.12*Math.sin(i*2*Math.PI*300/rate);}const activity=detectVocalActivity(samples,rate,100,10);assert.equal(activity.length,1);assert.ok(Math.abs(activity[0].s-.82)<.02);assert.ok(Math.abs(activity[0].e-2.98)<.02);const guide={mode:'free',lines:[],activity};assert.equal(linePart(guide,words,0,10),'A');assert.equal(linePart(guide,words,1,10),'B');assert.equal(linePart({...guide,activity:[{s:1,e:2}]},words,0,10),'partial');assert.equal(linePart({...guide,lines:['both']},words,0,10),'both');assert.equal(remainingRanges(activity,10).length,2);assert.deepEqual(detectVocalActivity(new Float32Array(rate),rate),[]);});
test('assigned and free guides persist and joiners cannot replace the first guide',async t=>{const f=await setup(t);for(const mode of ['lyrics','free']){const guide={version:1,mode,lines:['A','B'],...(mode==='free'?{activity:[{s:1,e:3}]}:{})};const r=await f.call('/api/covers','POST',{...body,duet_guide:guide},'other');assert.equal(r.status,201,JSON.stringify(r.body));f.sql.prepare("UPDATE tracks SET status='published' WHERE id=?").run(r.body.id);const loaded=(await f.call('/api/duets/'+r.body.id)).body;assert.deepEqual(loaded.duet.guide,guide);const joined=await f.call('/api/covers','POST',{...body,duet_slot:'second',duet_parent_id:r.body.id,duet_guide:{bad:true}},'owner');assert.equal(joined.status,201);assert.deepEqual(JSON.parse(f.sql.prepare('SELECT duet_guide FROM tracks WHERE id=?').get(joined.body.id).duet_guide),guide);}});
test('guide validation rejects incomplete assignments, invalid labels, unordered intervals and unbounded payloads',async t=>{const f=await setup(t);for(const guide of [{version:2,mode:'free'},{version:1,mode:'lyrics',lines:['A','']},{version:1,mode:'lyrics',lines:['A','A']},{version:1,mode:'lyrics',lines:['A','X']},{version:1,mode:'free',activity:[{s:3,e:4},{s:2,e:3}]},{version:1,mode:'free',activity:[{s:0,e:11}]},{version:1,mode:'free',activity:Array.from({length:601},()=>({s:0,e:1}))}])assert.equal((await f.call('/api/covers','POST',{...body,duet_guide:guide},'other')).status,400,JSON.stringify(guide));});

test('duet visual roles follow the current singer, with explicit shared and uncertain parts',()=>{assert.equal(lineRole('A',false),'mine');assert.equal(lineRole('B',false),'partner');assert.equal(lineRole('A',true),'partner');assert.equal(lineRole('B',true),'mine');for(const second of [false,true]){assert.equal(lineRole('both',second),'both');assert.equal(lineRole('partial',second),'partial');assert.equal(lineRole('',second),'');}});
